---
- name: Setup nginx for grafana
  hosts: monitoring
  become: yes
  gather_facts: True
  vars_prompt:
    - name: run_roles
      prompt: "Install nginx from scratch? (yes/no)"
      default: "no"
    - name: generate_certificates
      prompt: "Generate letsencrypt certificates? (yes/no)"
      default: "no"
  vars_files:
    - "vars/main.yml"
  roles:
    - role: nginxinc.nginx
      when: run_roles|bool
    - role: auxilincom.letsencrypt
      when: generate_certificates|bool and server_setup_letsencrypt_ssl|bool
  tasks:
    - name: setup nginx host file dirs
      file: name=/etc/nginx/{{ item }} state=directory owner=root group=root
      with_items:
        - sites-available
        - conf.d/http

    - name: Assures /etc/nginx/ssl exists
      file: path=/etc/nginx/ssl state=directory
      when: server_setup_ssl|bool

    - name: Copy ssl certiicate to /etc/nginx/ssl
      copy: src=ssl-keys/{{ item.src }} dest={{ item.dest }} owner=root mode=744
      with_items:
        - {src: 'app.crt', dest: '{{ server_ssl_cert_path }}'}
        - {src: 'app.key', dest: '{{ server_ssl_key_path }}'}
      when: server_setup_ssl|bool

    - name: Generate dhparams
      shell: openssl dhparam -out /etc/nginx/dhparams.pem 4096
      args:
        creates: /etc/nginx/dhparams.pem
      when: server_setup_letsencrypt_ssl|bool or server_setup_ssl|bool

    - name: copy nginx virtual host file
      template: src="templates/grafana-nginx-config.j2"
                dest="/etc/nginx/sites-available/03_monitoring"
                owner=root
                group=root
      when: not server_setup_letsencrypt_ssl|bool and not server_setup_ssl|bool

    - name: copy nginx virtual host file for ssl
      template: src="templates/grafana-nginx-config-with-ssl.j2"
                dest="/etc/nginx/sites-available/03_monitoring"
                owner=root
                group=root
      when: server_setup_letsencrypt_ssl|bool or server_setup_ssl|bool

    - name: link nginx virtual host file
      file: src="/etc/nginx/sites-available/03_monitoring"
            dest="/etc/nginx/conf.d/http/03_monitoring.conf"
            state=link

    - name: restart nginx
      service: name=nginx state=restarted
